server:
  port: 8000

spring:
  application:
    name: product
  data:
    mongodb:
      uri: mongodb://192.168.100.128:27017/product
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: 192.168.100.128:9200
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.100.128:3306/db_product?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 10
      maxActive: 30
      minIdle: 10
      maxWait: 2000
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
dubbo:
  application:
    name: product
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: icu.bitigo.product.service
  protocol:
    name: dubbo
    port: 20881
