server:
  port: 8006

spring:
  application:
    name: seller-admin
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: seller-admin
  registry:
    address: nacos://127.0.0.1:8848

